// S&P 500 主要銘柄リスト（約200銘柄）
export const SP500 = [
  // ── 情報技術 ──────────────────────────────────────────────────────
  { symbol: 'AAPL',  name: 'Apple' },
  { symbol: 'MSFT',  name: 'Microsoft' },
  { symbol: 'NVDA',  name: 'NVIDIA' },
  { symbol: 'AVGO',  name: 'Broadcom' },
  { symbol: 'ORCL',  name: 'Oracle' },
  { symbol: 'AMD',   name: 'AMD' },
  { symbol: 'QCOM',  name: 'Qualcomm' },
  { symbol: 'TXN',   name: 'Texas Instruments' },
  { symbol: 'AMAT',  name: 'Applied Materials' },
  { symbol: 'LRCX',  name: 'Lam Research' },
  { symbol: 'KLAC',  name: 'KLA Corporation' },
  { symbol: 'MU',    name: 'Micron Technology' },
  { symbol: 'INTC',  name: 'Intel' },
  { symbol: 'ADI',   name: 'Analog Devices' },
  { symbol: 'MCHP',  name: 'Microchip Technology' },
  { symbol: 'CDNS',  name: 'Cadence Design' },
  { symbol: 'SNPS',  name: 'Synopsys' },
  { symbol: 'MPWR',  name: 'Monolithic Power' },
  { symbol: 'ON',    name: 'ON Semiconductor' },
  { symbol: 'TEL',   name: 'TE Connectivity' },
  // ── ソフトウェア / クラウド ────────────────────────────────────────
  { symbol: 'CRM',   name: 'Salesforce' },
  { symbol: 'ADBE',  name: 'Adobe' },
  { symbol: 'NOW',   name: 'ServiceNow' },
  { symbol: 'INTU',  name: 'Intuit' },
  { symbol: 'WDAY',  name: 'Workday' },
  { symbol: 'PANW',  name: 'Palo Alto Networks' },
  { symbol: 'CRWD',  name: 'CrowdStrike' },
  { symbol: 'FTNT',  name: 'Fortinet' },
  { symbol: 'DDOG',  name: 'Datadog' },
  { symbol: 'ZS',    name: 'Zscaler' },
  { symbol: 'SNOW',  name: 'Snowflake' },
  { symbol: 'MDB',   name: 'MongoDB' },
  { symbol: 'PLTR',  name: 'Palantir' },
  { symbol: 'OKTA',  name: 'Okta' },
  { symbol: 'VEEV',  name: 'Veeva Systems' },
  { symbol: 'ANSS',  name: 'ANSYS' },
  { symbol: 'PTC',   name: 'PTC' },
  { symbol: 'IBM',   name: 'IBM' },
  // ── ハードウェア / ネットワーク ────────────────────────────────────
  { symbol: 'CSCO',  name: 'Cisco' },
  { symbol: 'HPQ',   name: 'HP' },
  { symbol: 'HPE',   name: 'Hewlett Packard Enterprise' },
  { symbol: 'DELL',  name: 'Dell Technologies' },
  { symbol: 'STX',   name: 'Seagate' },
  { symbol: 'WDC',   name: 'Western Digital' },
  { symbol: 'NTAP',  name: 'NetApp' },
  { symbol: 'JNPR',  name: 'Juniper Networks' },
  // ── 通信サービス ────────────────────────────────────────────────
  { symbol: 'GOOGL', name: 'Alphabet (A)' },
  { symbol: 'META',  name: 'Meta Platforms' },
  { symbol: 'NFLX',  name: 'Netflix' },
  { symbol: 'DIS',   name: 'Disney' },
  { symbol: 'CMCSA', name: 'Comcast' },
  { symbol: 'T',     name: 'AT&T' },
  { symbol: 'VZ',    name: 'Verizon' },
  { symbol: 'TMUS',  name: 'T-Mobile' },
  { symbol: 'CHTR',  name: 'Charter Communications' },
  { symbol: 'EA',    name: 'Electronic Arts' },
  { symbol: 'TTWO',  name: 'Take-Two Interactive' },
  { symbol: 'ATVI',  name: 'Activision Blizzard' },
  { symbol: 'WBD',   name: 'Warner Bros Discovery' },
  { symbol: 'PARA',  name: 'Paramount Global' },
  // ── 一般消費財 ─────────────────────────────────────────────────
  { symbol: 'AMZN',  name: 'Amazon' },
  { symbol: 'TSLA',  name: 'Tesla' },
  { symbol: 'HD',    name: 'Home Depot' },
  { symbol: 'MCD',   name: "McDonald's" },
  { symbol: 'NKE',   name: 'Nike' },
  { symbol: 'SBUX',  name: 'Starbucks' },
  { symbol: 'LOW',   name: "Lowe's" },
  { symbol: 'TGT',   name: 'Target' },
  { symbol: 'BKNG',  name: 'Booking Holdings' },
  { symbol: 'MAR',   name: 'Marriott' },
  { symbol: 'HLT',   name: 'Hilton' },
  { symbol: 'ABNB',  name: 'Airbnb' },
  { symbol: 'UBER',  name: 'Uber' },
  { symbol: 'LYFT',  name: 'Lyft' },
  { symbol: 'GM',    name: 'General Motors' },
  { symbol: 'F',     name: 'Ford Motor' },
  { symbol: 'RIVN',  name: 'Rivian' },
  { symbol: 'LCID',  name: 'Lucid Group' },
  { symbol: 'EBAY',  name: 'eBay' },
  { symbol: 'ETSY',  name: 'Etsy' },
  { symbol: 'ROST',  name: 'Ross Stores' },
  { symbol: 'TJX',   name: 'TJX Companies' },
  { symbol: 'DHI',   name: 'D.R. Horton' },
  { symbol: 'LEN',   name: 'Lennar' },
  // ── 生活必需品 ─────────────────────────────────────────────────
  { symbol: 'WMT',   name: 'Walmart' },
  { symbol: 'COST',  name: 'Costco' },
  { symbol: 'PG',    name: 'Procter & Gamble' },
  { symbol: 'KO',    name: 'Coca-Cola' },
  { symbol: 'PEP',   name: 'PepsiCo' },
  { symbol: 'PM',    name: 'Philip Morris' },
  { symbol: 'MO',    name: 'Altria' },
  { symbol: 'CL',    name: 'Colgate-Palmolive' },
  { symbol: 'KMB',   name: 'Kimberly-Clark' },
  { symbol: 'GIS',   name: 'General Mills' },
  { symbol: 'K',     name: 'Kellanova' },
  { symbol: 'HRL',   name: 'Hormel Foods' },
  { symbol: 'SYY',   name: 'Sysco' },
  { symbol: 'KR',    name: 'Kroger' },
  // ── ヘルスケア ─────────────────────────────────────────────────
  { symbol: 'UNH',   name: 'UnitedHealth' },
  { symbol: 'LLY',   name: 'Eli Lilly' },
  { symbol: 'JNJ',   name: 'Johnson & Johnson' },
  { symbol: 'ABBV',  name: 'AbbVie' },
  { symbol: 'MRK',   name: 'Merck' },
  { symbol: 'PFE',   name: 'Pfizer' },
  { symbol: 'TMO',   name: 'Thermo Fisher' },
  { symbol: 'ABT',   name: 'Abbott Laboratories' },
  { symbol: 'AMGN',  name: 'Amgen' },
  { symbol: 'GILD',  name: 'Gilead Sciences' },
  { symbol: 'CVS',   name: 'CVS Health' },
  { symbol: 'MCK',   name: 'McKesson' },
  { symbol: 'CI',    name: 'Cigna' },
  { symbol: 'ELV',   name: 'Elevance Health' },
  { symbol: 'HUM',   name: 'Humana' },
  { symbol: 'MDT',   name: 'Medtronic' },
  { symbol: 'SYK',   name: 'Stryker' },
  { symbol: 'BSX',   name: 'Boston Scientific' },
  { symbol: 'EW',    name: 'Edwards Lifesciences' },
  { symbol: 'ISRG',  name: 'Intuitive Surgical' },
  { symbol: 'VRTX',  name: 'Vertex Pharmaceuticals' },
  { symbol: 'REGN',  name: 'Regeneron' },
  { symbol: 'BIIB',  name: 'Biogen' },
  { symbol: 'MRNA',  name: 'Moderna' },
  { symbol: 'ILMN',  name: 'Illumina' },
  { symbol: 'ZBH',   name: 'Zimmer Biomet' },
  { symbol: 'BAX',   name: 'Baxter International' },
  // ── 金融 ───────────────────────────────────────────────────────
  { symbol: 'JPM',   name: 'JPMorgan Chase' },
  { symbol: 'BAC',   name: 'Bank of America' },
  { symbol: 'WFC',   name: 'Wells Fargo' },
  { symbol: 'GS',    name: 'Goldman Sachs' },
  { symbol: 'MS',    name: 'Morgan Stanley' },
  { symbol: 'C',     name: 'Citigroup' },
  { symbol: 'USB',   name: 'U.S. Bancorp' },
  { symbol: 'PNC',   name: 'PNC Financial' },
  { symbol: 'TFC',   name: 'Truist Financial' },
  { symbol: 'COF',   name: 'Capital One' },
  { symbol: 'AXP',   name: 'American Express' },
  { symbol: 'V',     name: 'Visa' },
  { symbol: 'MA',    name: 'Mastercard' },
  { symbol: 'PYPL',  name: 'PayPal' },
  { symbol: 'SQ',    name: 'Block' },
  { symbol: 'AFRM',  name: 'Affirm' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway' },
  { symbol: 'BLK',   name: 'BlackRock' },
  { symbol: 'SCHW',  name: 'Charles Schwab' },
  { symbol: 'SPGI',  name: 'S&P Global' },
  { symbol: 'CME',   name: 'CME Group' },
  { symbol: 'ICE',   name: 'Intercontinental Exchange' },
  { symbol: 'MCO',   name: "Moody's" },
  { symbol: 'AON',   name: 'Aon' },
  { symbol: 'MMC',   name: 'Marsh & McLennan' },
  // ── 資本財 ─────────────────────────────────────────────────────
  { symbol: 'CAT',   name: 'Caterpillar' },
  { symbol: 'DE',    name: 'Deere & Company' },
  { symbol: 'HON',   name: 'Honeywell' },
  { symbol: 'GE',    name: 'GE Aerospace' },
  { symbol: 'BA',    name: 'Boeing' },
  { symbol: 'LMT',   name: 'Lockheed Martin' },
  { symbol: 'RTX',   name: 'RTX Corporation' },
  { symbol: 'NOC',   name: 'Northrop Grumman' },
  { symbol: 'GD',    name: 'General Dynamics' },
  { symbol: 'UNP',   name: 'Union Pacific' },
  { symbol: 'CSX',   name: 'CSX' },
  { symbol: 'NSC',   name: 'Norfolk Southern' },
  { symbol: 'UPS',   name: 'UPS' },
  { symbol: 'FDX',   name: 'FedEx' },
  { symbol: 'MMM',   name: '3M' },
  { symbol: 'EMR',   name: 'Emerson Electric' },
  { symbol: 'ETN',   name: 'Eaton' },
  { symbol: 'PH',    name: 'Parker-Hannifin' },
  { symbol: 'ROK',   name: 'Rockwell Automation' },
  { symbol: 'ITW',   name: 'Illinois Tool Works' },
  { symbol: 'PCAR',  name: 'PACCAR' },
  { symbol: 'CTAS',  name: 'Cintas' },
  { symbol: 'FAST',  name: 'Fastenal' },
  { symbol: 'WM',    name: 'Waste Management' },
  { symbol: 'RSG',   name: 'Republic Services' },
  // ── エネルギー ─────────────────────────────────────────────────
  { symbol: 'XOM',   name: 'Exxon Mobil' },
  { symbol: 'CVX',   name: 'Chevron' },
  { symbol: 'COP',   name: 'ConocoPhillips' },
  { symbol: 'EOG',   name: 'EOG Resources' },
  { symbol: 'SLB',   name: 'SLB (Schlumberger)' },
  { symbol: 'MPC',   name: 'Marathon Petroleum' },
  { symbol: 'PSX',   name: 'Phillips 66' },
  { symbol: 'VLO',   name: 'Valero Energy' },
  { symbol: 'OXY',   name: 'Occidental Petroleum' },
  { symbol: 'HAL',   name: 'Halliburton' },
  { symbol: 'BKR',   name: 'Baker Hughes' },
  // ── 素材 ───────────────────────────────────────────────────────
  { symbol: 'LIN',   name: 'Linde' },
  { symbol: 'APD',   name: 'Air Products' },
  { symbol: 'SHW',   name: 'Sherwin-Williams' },
  { symbol: 'ECL',   name: 'Ecolab' },
  { symbol: 'DD',    name: 'DuPont' },
  { symbol: 'DOW',   name: 'Dow' },
  { symbol: 'NEM',   name: 'Newmont' },
  { symbol: 'FCX',   name: 'Freeport-McMoRan' },
  { symbol: 'NUE',   name: 'Nucor' },
  { symbol: 'VMC',   name: 'Vulcan Materials' },
  { symbol: 'MLM',   name: 'Martin Marietta' },
  // ── 不動産 / 公益 ───────────────────────────────────────────────
  { symbol: 'PLD',   name: 'Prologis' },
  { symbol: 'AMT',   name: 'American Tower' },
  { symbol: 'EQIX',  name: 'Equinix' },
  { symbol: 'CCI',   name: 'Crown Castle' },
  { symbol: 'SPG',   name: 'Simon Property Group' },
  { symbol: 'O',     name: 'Realty Income' },
  { symbol: 'NEE',   name: 'NextEra Energy' },
  { symbol: 'DUK',   name: 'Duke Energy' },
  { symbol: 'SO',    name: 'Southern Company' },
  { symbol: 'D',     name: 'Dominion Energy' },
  { symbol: 'AEP',   name: 'AEP' },
  // ── その他注目銘柄 ──────────────────────────────────────────────
  { symbol: 'ACN',   name: 'Accenture' },
  { symbol: 'COIN',  name: 'Coinbase' },
  { symbol: 'MSTR',  name: 'MicroStrategy' },
  { symbol: 'HOOD',  name: 'Robinhood' },
  { symbol: 'SOFI',  name: 'SoFi Technologies' },
  { symbol: 'RBLX',  name: 'Roblox' },
  { symbol: 'SPOT',  name: 'Spotify' },
  { symbol: 'PATH',  name: 'UiPath' },
  { symbol: 'AI',    name: 'C3.ai' },
  { symbol: 'IONQ',  name: 'IonQ' },
  { symbol: 'RGTI',  name: 'Rigetti Computing' },
];
